### ISSUE TITLE
Files missing!

### ISSUE THREAD

**Issue by ziyangli** [ethz-asl/ros-drivers#5]
vicon_bridge/Markers.h
vicon_bridge/Marker.h
vicon_bridge/viconCalibrateSegment.h

But I can not find these files!

**Comment by markusachtelik** [comment]
for the first two, make sure that the messages in vicon_bridge build. Where are these files included? Anyway, if you just use vicon_bridge, it lives in another repo now: https://github.com/ethz-asl/vicon_bridge, which I would recommend to use.

**Comment by ziyangli** [comment]
Sorry, those files will be auto generated from messages and services.
