### ISSUE TITLE
ViconDataStreamSDK_CPPTest.cpp:108:12: error: ‘sleep’ was not declared in this scope

### ISSUE THREAD

**Issue by SharmaNishant** [ethz-asl/ros-drivers#8]
In file  "ViconDataStreamSDK_CPPTest.cpp" - rosmake on Ubuntu gives an error saying that sleep was not declared in this scope.

the code is like this:
# include "Client.h"
# include <iostream>
# ifdef WIN32

  #include <conio.h>   // For _kbhit()
  #include <windows.h> // For Sleep()
# endif // WIN32

updated version (it works):
# include "Client.h"
# include <iostream>
# ifdef WIN32

  #include <conio.h>   // For _kbhit()
  #include <windows.h> // For Sleep()
# else

  #include <unistd.h>
# endif // WIN32

Please update the same in repository.

**Comment by markusachtelik** [comment]
I can't really see what you're newly including -- would you mind opening a PR? and actually preferably on this repo: https://github.com/ethz-asl/vicon_bridge

**Comment by SharmaNishant** [comment]
I just saw that it's already been taken care of in the new repo.
